"""create users and food_entries

Revision ID: 9ac5c800f158
Revises: 
Create Date: 2026-08-29 14:57:57.478096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac5c800f158'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('food_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('meal_category', sa.String(length=20), nullable=False),
    sa.Column('food_name', sa.String(length=200), nullable=False),
    sa.Column('serving_description', sa.String(length=200), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carb_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('calories >= 0', name='ck_food_entries_calories_non_negative'),
    sa.CheckConstraint('carb_g >= 0', name='ck_food_entries_carb_non_negative'),
    sa.CheckConstraint('fat_g >= 0', name='ck_food_entries_fat_non_negative'),
    sa.CheckConstraint('protein_g >= 0', name='ck_food_entries_protein_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_entries_entry_date'), 'food_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_food_entries_user_id'), 'food_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_entries_user_id'), table_name='food_entries')
    op.drop_index(op.f('ix_food_entries_entry_date'), table_name='food_entries')
    op.drop_table('food_entries')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
